# These are supported funding model platforms

github: [DivyanshuSingh96]  # Replace with your GitHub username
custom: ['https://www.paypal.com/paypalme/divyanshu3690']  # Replace with your PayPal link
